---
- hosts: localhost
  connection: local

  vars_files:
    - vars/automatic_main.yml

  vars_prompt:
    - name: "editor"
      prompt: "What is the path to your default editor?"
      default: "/usr/bin/mate"
      private: no
    - name: "git_name"
      prompt: "What would you like to set your git name to?"
      private: no
    - name: "git_email"
      prompt: "How about your git email?"
      private: no

  tasks:
    - name: Ensure Ansible downloads directory exists.
      file:
        path: "{{ downloads }}"
        state: directory

    - name: Ensure development diretory exists
      file:
        path: "{{ dev_directory }}"
        state: directory

    - name: Tap brew kegs
      homebrew_tap: tap={{ item }}
      with_items: homebrew_taps

    - name: Install homebrew packages
      homebrew:
        name: "{{ item }}"
        update_homebrew: yes
      with_items: homebrew_installed_packages

    - name: Install homebrew cask applications
      homebrew_cask: name={{ item }}
      with_items: homebrew_cask_apps

    - name: Install npm dependencies
      npm:
        name: "{{ item }}"
        global: yes
      with_items: npm_packages

    - include: tasks/preferences.yml
    - include: tasks/python.yml
    - include: tasks/arcanist.yml
    - include: tasks/bash_it.yml
